[tool.poetry]
name = "budgly"
version = "0.1.0"
description = "Server API to track expenses and do some KPI"
authors = ["Alexis THIBAULT <alexis.thibault31@gmail.com>"]
license = "LICENSE"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
uvicorn = { extras = ["standard"], version = "^0.29.0" }
fastapi = "^0.111.0"
pydantic = "^2.7.1"
sqlmodel = "^0.0.16"
alembic = "^1.13.1"
psycopg = { extras = ["binary"], version = "^3.1.18" }
pydantic-settings = "^2.2.1"
tenacity = "^8.2.3"
sqlalchemy-utils = "^0.41.2"
firebase-admin = "^6.5.0"
httpx = "^0.27.0"
google-auth-oauthlib = "^1.2.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.1.1"
mypy = "^1.9.0"
ruff = "^0.3.7"
coverage = "^7.4.4"
pre-commit = "^3.7.0"
isort = "^5.13.2"
black = "^24.4.0"
pytest-cov = "^5.0.0"
factory-boy = "^3.3.0"
sqlalchemy = { extras = ["mypy"], version = "^2.0.29" }
types-sqlalchemy-utils = "^1.0.1"
types-factory-boy = "^0.4.1"
pytest-mock = "^3.14.0"
python-jose = { extras = ["cryptography"], version = "^3.3.0" }
types-oauthlib = "^3.2.0.20240217"
types-python-jose = "^3.3.4.20240106"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
cache_dir = ".pytest_cache"
python_files = "tests_*.py"
filterwarnings = [
    'ignore:datetime\.datetime\.utcnow\(\) is deprecated and scheduled for removal in a future version\..*:DeprecationWarning:jose',
]

[tool.coverage.run]
omit = [
    "alembic/*",
    "**/__init__.py",
    "scripts/*",
    "tests/*",
]

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
line_length = 88

[tool.mypy]
strict = true
exclude = ["alembic", "tests.factories"]
plugins = [
    "pydantic.mypy",
]

[tool.ruff]
target-version = "py310"
exclude = ["alembic"]

[tool.ruff.lint]
select = [
    "E",
    "W",
    "F",
    "I",
    "B",
    "C4",
    "UP",
]
ignore = [
    "E501",
    "B008",
    "W191",
    "B904",
]

[tool.ruff.lint.pyupgrade]
keep-runtime-typing = true
